## roles/vim/tasks/CentOS.yml
## CentOS specific tasks
# vim:ft=ansible:
---
- name: "vim-plug install"
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: '{{ item.value}}{{ item.key}}.vim/autoload/plug.vim'
  tags: vim,editor
...

