## roles/vim/tasks/CentOS.yml
## CentOS specific tasks
# vim:ft=ansible:
---
- name: "vim-plug install"
  become: yes
  become_user: '{{ as_user }}'
  command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags: vim,editor
...

